### ISSUE TITLE
accès CFA erreur de connexion

### ISSUE THREAD

**Issue by nadinelouchart** [mission-apprentissage/flux-retour-cfas#2624]
![Image](https://user-images.githubusercontent.com/121936073/220135155-5a379c46-2d9c-4cc0-a84d-e1619240a9ee.png)

Problème accès CFA

**Comment by totakoko** [comment]
@sbenfares J'ai fait quelques corrections dans #2626 mais ce n'est pas la même erreur qui est rencontrée.

D'après les logs, la première erreur recontrée est `Plan executor error during findAndModify :: caused by :: Document failed validation` avec errinfo :
```json
{
  "failingDocumentId": "63ee4f776e3e5e06557485f2",
  "details": {
    "operatorName": "$jsonSchema",
    "title": "organismes validation schema",
    "schemaRulesNotSatisfied": [
      {
        "operatorName": "properties",
        "propertiesNotSatisfied": [
          {
            "propertyName": "uai",
            "description": "Code UAI de l'établissement",
            "details": [
              {
                "operatorName": "bsonType",
                "specifiedAs": {
                  "bsonType": "string"
                },
                "reason": "type did not match",
                "consideredValue": null,
                "consideredType": "null"
              }
            ]
          }
        ]
      }
    ]
  }
}
```
Si on retente, on obtient une autre erreur liée à un doublon dans la collection permissions.
```
E11000 duplicate key error collection: flux-retour-cfas.permissions index: organisme_id_1_userEmail_1_role_1 dup key: { organisme_id: ObjectId('63ee4f776e3e5e06557485f2'), userEmail: \"of-19560013500063@test.fr\", role: ObjectId('63c7cb969fb22d361ffc7b2b') }
```

Je soupconne l'erreur d'origine de survenir dans la fonction [addContributeurOrganisme](https://github.com/mission-apprentissage/flux-retour-cfas/blob/f0eb9a4e364b0561cdeaca582312cd7a24c57562/server/src/common/actions/organismes/organismes.actions.js#L306-L319) (appelé depuis userAfterCreate) au moment de créer les permissions mais je n'ai pas réussi à reproduire le bug en local.

C'est peut-être un effet de bord de la récente PR #2598 ?

**Comment by totakoko** [comment]
Après des corrections dans #2626, j'ai pu valider une création de compte + validation par l'admin. Est-ce que tu pourras retester ? @nadinelouchart
